apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../base
images:
  - name: 065967698083.dkr.ecr.eu-west-3.amazonaws.com/gitops-demo-backend
    newTag: latest
  - name: 065967698083.dkr.ecr.eu-west-3.amazonaws.com/gitops-demo-frontend
    newTag: latest
