apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: dev
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 065967698083.dkr.ecr.eu-west-3.amazonaws.com/gitops-demo-backend:latest
          ports:
            - containerPort: 80
