apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: dev
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 065967698083.dkr.ecr.eu-west-3.amazonaws.com/gitops-demo-frontend:latest
          ports:
            - containerPort: 80
